# Generated by Django 2.0 on 2019-01-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luck_name', models.CharField(max_length=20)),
                ('actor_obj', models.OneToOneField(on_delete=True, to='main.ActorTable')),
            ],
        ),
    ]
