# Generated by Django 2.0 on 2019-01-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lucktable'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField()),
            ],
        ),
    ]
