# Generated by Django 2.0 on 2019-01-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_starttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='actortable',
            name='lucked',
            field=models.BooleanField(default=False),
        ),
    ]
